version: '3.8'

services:
  app:
    build: .
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - PORT=1337
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:1337/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment if you want to add a database
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: sails_app
  #     POSTGRES_USER: sails_user
  #     POSTGRES_PASSWORD: sails_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
