# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Grype vulnerability scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Anchore Syft SBOM scan" ]
    branches: [main]
    types: [ completed ]

permissions:
  actions: read
  contents: read

jobs:
  Anchore-Build-Scan:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read # for actions/checkout to fetch code
      actions: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Echo triggering run id
      run: echo "TRIGGER RUN- ${{ github.event.workflow_run.id }}"
    - name: Debug list artifacts on triggering run
      run: |
        curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts \
          | jq -r '.artifacts[].name'

    - name: Download SBOM artifact from Syft workflow
      uses: actions/download-artifact@v4
      with:
        name: image-sbom.cdx.json
        run-id: ${{ github.event.workflow_run.id }}
        path: .
    - name: Scan SBOM
      uses: anchore/scan-action@v6
      id: scan
      with:
        sbom: "image-sbom.cdx.json"
        fail-build: true
        severity-cutoff: critical
    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
