# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft
name: Anchore Syft SBOM scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag localbuild/image:latest
        docker save localbuild/image:latest -o image.tar
    - name: Scan the image and upload SBOM artifact
      uses: anchore/sbom-action@v0.20.5
      with:
        image: "localbuild/image:latest"
        format: "cyclonedx-json"
        output-file: "image-sbom.cdx.json"
        artifact-name: image-sbom.cdx.json
        dependency-snapshot: true
    - name: Attest SBOM
      uses: actions/attest-sbom@v2
      with:
        subject-path: 'image.tar'
        sbom-path: 'image-sbom.cdx.json'
    - name: Upload image for verification
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar